
///Dimens
const double MARGIN_PRE_SMALL = 4.0;
const double MARGIN_SMALL = 6.0;
const double MARGIN_SMALL_1 = 8.0;
const double MARGIN_SMALL_1X = 10.0;
const double MARGIN_MEDIUM = 12.0;
const double MARGIN_FOR_CHECK_ICON = 13.0;
const double MARGIN_MEDIUM_1 = 16.0;
const double MARGIN_MEDIUM_1X = 18.0;
const double MARGIN_MEDIUM_2 = 20.0;
const double MARGIN_MEDIUM_2X = 22.0;
const double MARGIN_SIZE_FOR_APP_BAR_ICON = 28.0;
const double MARGIN_SIZE_FOR_ICON = 32.0;
const double NEW_POST_BTM_SHEET_UP_ICON_SIZE = 36.0;
const double MARGIN_SIZE_FOR_REGISTER_SPACEING = 40.0;
const double DISCOVER_POST_COMMENT_SECTION_PADDING = 30.0;
const double ICON_SIZE_FOR_VARIFACATION = 48.0;
const double MARGIN_FOR_CONTACT_NAME_TITLE = 60.0;
const double MARGIN_PROFILE_CIRCLE = 63.0;
const double MARGIN_FOR_LOGIN_PAGE_SPACING = 64.0;
const double MARGIN_HEIGHT_FOR_SPACING = 82.0;
const double MARGIN_SIZE_FOR_CHAT = 100.0;
const double MARGIN_SIZE_FOR_SPACING = 220.0;



///TEXT
const double TEXT_SMALL = 8.0;
const double TEXT_SMALL_1 = 10.0;
const double TEXT_SMALL_1X = 12.0;
const double TEXT_MEDIUM = 14.0;
const double TEXT_MEDIUM_1 = 16.0;
const double TEXT_MEDIUM_1X = 18.0;
const double TEXT_LARGE = 20.0;
const double TEXT_LARGE_1 = 22.0;



///Widget
const double CHOOSEN_PHOTO_CONTAINER_HEIGHT = 100.0;
const double CHOOSEN_PHOTO_HEIGHT = 80.0;
const double CHOOSEN_PHOTO_WIDTH = 120.0;
const double CHECK_ICON_WIDTH = 26.0;
const double CHECK_ICON_HEIGHT = 26.0;
const double ACCEPT_AND_CONTINUE_CONTAINER_HEIGHT = 50.0;
const double FUNCTIION_ICON_CONTAINER_WIDTH = 60.0;
const double FUNCTIION_ICON_CONTAINER_HEIGHT = 70.0;
const double CONTACT_NAME_LIST_TITLE_CONTAINGER_HEIGHT = 40.0;
const double PROFILE_CONTAINER_WIDTH = 80.0;
const double CONTACT_ICON_ROW_CONTAINER_HEIGHT = 100.0;
const double DIVIDE_VERTICAL_LINE = 100.0;
const double ME_TAB_PROFILE_CONTAINER_HEIGHT =  126.0;
const double ME_TAB_PROFILE_CONTAINER_WIDTH =  126.0;
const double LOGOUT_BTN_CONTAINER_HEIGHT = 46.0;
const double COMMENT_SECTION_ICON_WIDTH = 20.0;
const double DISCOVER_POST_USER_NAME_PADDING = 56.0;
const double CONSERVATION_SEND_VIDEO_WIDTH = 200.0;
const double LOGIN_BTN_CONTAINER_WIDTH = 140.0;
const double LOGIN_BTN_CONTAINER_HEIGHT = 50.0;
const double LOADING_VIEW_CONTAINER_WIDTH = 120.0;
const double LOADING_VIEW_CONTAINER_HEIGHT = 120.0;